'use client';
import {useEffect,useState} from 'react';
import {Search,RefreshCw,ArrowUpRight} from 'lucide-react';
import SiteHeader from '../site-header';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {readGallery} from '@/lib/gallery';
import {readBird,openSeaBirdUrl,type Bird} from '@/lib/birds';
import {readMintState} from '@/lib/ink-contract';
export default function Gallery(){
 const [birds,setBirds]=useState<Bird[]>([]),[next,setNext]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Bird|null>(null),[query,setQuery]=useState(''),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState(''),[supply,setSupply]=useState<number|null>(null);
 async function load(more=false){setLoading(true);setError('');try{const result=await readGallery(more?next||undefined:undefined);setBirds(old=>more?[...old,...result.birds.filter(b=>!old.some(o=>o.id===b.id))]:result.birds);setNext(result.next);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();let active=true;const update=()=>readMintState().then(s=>{if(active)setSupply(s.supply);}).catch(()=>{});update();const timer=setInterval(update,30000);return()=>{active=false;clearInterval(timer);};},[]);
 async function search(e:React.FormEvent){e.preventDefault();setSearchError('');if(!/^\d+$/.test(query)||Number(query)<1||Number(query)>10000){setSearchError('Enter a bird number from 1 to 10,000.');return;}setSearching(true);try{setSelected(await readBird(String(Number(query))));}catch{setSearchError('This bird has not been minted yet, or its artwork is still being indexed.');}finally{setSearching(false);}}
 return <div className="site-shell"><SiteHeader current="gallery"/><main className="birds-page"><div className="workspace-heading"><div><p className="eyebrow">10,000 PIXEL PERSONALITIES</p><h1>The flock<span>.</span></h1><p>The collection, as it hatches. No wallet needed.</p></div><div className="gallery-count"><strong>{supply===null?'—':supply.toLocaleString('en-US')}</strong> / 10,000 minted</div></div><div className="gallery-toolbar"><form onSubmit={search}><label className="sr-only" htmlFor="bird-search">Bird number</label><Search size={18}/><input id="bird-search" inputMode="numeric" placeholder="Find a bird by number" value={query} onChange={e=>setQuery(e.target.value)} maxLength={5}/><button disabled={searching}>{searching?'Finding…':'Find'}</button></form><button className="connect-button" disabled={loading} onClick={()=>load()}><RefreshCw size={16}/> Refresh gallery</button></div>{searchError&&<p role="alert" className="tool-error">{searchError}</p>}<div className="birds-grid gallery-grid">{birds.map(b=><button className="bird-card gallery-bird" key={b.id} onClick={()=>setSelected(b)}><div className="bird-art">{b.image?<img src={b.image} alt={b.name} loading="lazy" width={400} height={400}/>:<div className="bird-placeholder">#{b.id}</div>}</div><div className="bird-card-body"><h2>{b.name}</h2><span>View bird <ArrowUpRight size={14}/></span></div></button>)}</div>{error&&<p className="tool-error" role="alert">{error}</p>}{loading&&<p className="gallery-status" role="status">Gathering the flock…</p>}{!loading&&(next||error)&&<button className="load-more connect-button" onClick={()=>load(birds.length>0)}>{error?'Try again':'Load more birds'}</button>}{!loading&&!error&&birds.length===0&&<p className="gallery-status">The first birds will appear here once minted.</p>}<p className="ownership-note">Newest minted birds first. Artwork may take a moment to appear after minting.</p></main><Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="bird-detail"><div className="bird-detail-image">{selected?.image&&<img src={selected.image} alt={selected.name}/>}</div><div className="bird-detail-info"><p className="eyebrow">INKBIRDS · ON INK</p><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>Collection bird #{selected?.id}</DialogDescription><dl>{selected?.traits.map((t,i)=><div key={i}><dt>{t.label}</dt><dd>{t.value}</dd></div>)}</dl><a className="mint-button" href={selected?openSeaBirdUrl(selected.id):undefined} target="_blank" rel="noopener noreferrer">View on OpenSea <ArrowUpRight size={18}/></a></div></DialogContent></Dialog></div>;
}
