"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {Wallet,ArrowUpRight,RefreshCw,ChevronLeft,ChevronRight} from "lucide-react";
import SiteHeader from "../site-header";
import BirdCard from "../bird-card";
import {readOwnedBirds} from "@/lib/birds";
import {useWallet,openWallet} from "@/lib/wallet";

const PAGE_SIZE=12;
export default function MyBirds(){
  const {address}=useWallet();const [data,setData]=useState<{address:string;ids:string[];block:number}|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [refresh,setRefresh]=useState(0);const [page,setPage]=useState(0);
  useEffect(()=>{setPage(0);setData(null);setError("");if(!address){setLoading(false);return;}let active=true;setLoading(true);readOwnedBirds(address).then(result=>{if(active)setData({...result,address});}).catch(()=>{if(active)setError("We couldn’t load your birds from Ink. Your NFTs are still in your wallet. Please retry.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[address,refresh]);
  useEffect(()=>{const show=(event:Event)=>setError((event as CustomEvent).detail);window.addEventListener("inkbirds-wallet-error",show);const reload=()=>setRefresh(x=>x+1);window.addEventListener("inkbirds-minted",reload);return()=>{window.removeEventListener("inkbirds-wallet-error",show);window.removeEventListener("inkbirds-minted",reload);};},[]);
  const owned=data&&data.address===address?data:null;
  const count=owned?.ids.length??0;const pages=Math.ceil(count/PAGE_SIZE);
  return <div className="site-shell"><SiteHeader current="birds"/><main className="birds-page"><section className="intro birds-intro"><div><p className="eyebrow">YOUR CORNER OF THE FLOCK</p><h1>My Birds<span className="heading-period">.</span></h1><p className="birds-description">All the Inkbirds that call your wallet home.</p></div>{address&&<button className="connect-button" disabled={loading} onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Refreshing…':'Refresh birds'}</button>}</section>
  {!address?<section className="birds-empty"><span className="empty-icon"><Wallet size={28}/></span><p className="eyebrow">ONE WALLET. YOUR WHOLE FLOCK.</p><h2>Let’s find your birds.</h2><p>Connect your wallet to view your Inkbirds.<br/>No signature or transaction required.</p><button className="mint-button" onClick={()=>openWallet()}><Wallet size={18}/>Connect wallet</button>{error&&<p role="alert">{error}</p>}</section>:loading?<section className="birds-loading" role="status"><RefreshCw className="spin" size={24}/><h2>Gathering your flock…</h2><p>Checking ownership directly on Ink.</p></section>:error?<section className="birds-empty" role="alert"><h2>Your flock is taking a moment.</h2><p>{error}</p><button className="mint-button" onClick={()=>setRefresh(x=>x+1)}>Try again</button></section>:owned&&count===0?<section className="birds-empty"><p className="eyebrow">ROOM FOR YOUR FIRST BIRD</p><h2>Your flock starts here.</h2><p>This wallet doesn’t hold any Inkbirds yet.</p><Link className="mint-button" href="/">Mint an Inkbird <ArrowUpRight size={18}/></Link><a className="secondary-link" href="https://opensea.io/collection/inkbirdsnft" target="_blank" rel="noopener noreferrer">Explore on OpenSea <ArrowUpRight size={15}/></a></section>:owned?<><div className="collection-summary"><div><strong>{count.toLocaleString('en-US')}</strong> {count===1?'bird':'birds'} in your wallet</div><span>{address.slice(0,6)}…{address.slice(-4)} · Ink</span></div><div className="birds-grid">{owned.ids.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE).map(id=><BirdCard key={`${address}-${id}`} id={id}/>)}</div>{pages>1&&<nav className="birds-pagination" aria-label="My Birds pages"><button onClick={()=>setPage(p=>p-1)} disabled={page===0}><ChevronLeft size={18}/> Previous</button><span>Page {page+1} of {pages}</span><button onClick={()=>setPage(p=>p+1)} disabled={page>=pages-1}>Next <ChevronRight size={18}/></button></nav>}<p className="ownership-note">Ownership checked on Ink · Block {owned.block.toLocaleString('en-US')}. Refresh after a transfer.</p></>:null}
  </main><footer><span>INKBIRDS <span className="footer-year">© 2026</span></span><Link href="/">Back to mint <ArrowUpRight size={14}/></Link><span className="footer-chain">DIFFERENT FEATHERS. SAME FLOCK.</span></footer></div>;
}
